/*
 * Copyright © 2015 Integrated Knowledge Management (support@ikm.dev)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.ikm.tinkar.integration.changeSet;

import org.junit.platform.suite.api.SelectClasses;
import org.junit.platform.suite.api.Suite;
import org.junit.platform.suite.api.SuiteDisplayName;

/**
 * Test suite that ensures correct execution order for forward reference changeset tests.
 *
 * <p>This suite guarantees that:
 * <ol>
 *   <li>{@link ForwardReferenceChangeSetGenerateStep} runs FIRST to generate the changeset file</li>
 *   <li>{@link ForwardReferenceChangeSetIngestStep} runs SECOND to test importing the changeset</li>
 * </ol>
 *
 * <p>Test Execution Flow:
 * <pre>
 * 1. ForwardReferenceChangeSetGenerateIT
 *    - Starts in fresh JVM
 *    - Creates changeset with forward reference (semantic before concept)
 *    - Outputs: forward-reference-changeset.zip
 *    - JVM terminates
 *
 * 2. ForwardReferenceChangeSetIngestIT
 *    - Starts in fresh JVM
 *    - Imports changeset using multi-pass algorithm
 *    - Verifies forward references resolved correctly
 *    - JVM terminates
 * </pre>
 *
 * <p>Why This Suite Is Necessary:
 * <ul>
 *   <li>Only one PrimitiveData instance can run per JVM</li>
 *   <li>Generate test must complete before Ingest test starts</li>
 *   <li>Ingest test depends on file generated by Generate test</li>
 *   <li>Maven Surefire with reuseForks=false gives each test class a fresh JVM</li>
 * </ul>
 *
 * <p>Configuration:
 * <ul>
 *   <li>Maven Surefire: {@code <runOrder>alphabetical</runOrder>} for consistent ordering</li>
 *   <li>Maven Surefire: {@code <parallel>none</parallel>} for sequential execution</li>
 *   <li>Maven Surefire: {@code <reuseForks>false</reuseForks>} for JVM isolation</li>
 * </ul>
 *
 * <p>To run this suite:
 * <pre>
 * mvn clean test -Dtest=ForwardReferenceChangeSetTestSuite
 * </pre>
 *
 * @see ForwardReferenceChangeSetGenerateStep
 * @see ForwardReferenceChangeSetIngestStep
 */
@Suite
@SuiteDisplayName("Forward Reference Changeset Test Suite")
@SelectClasses({
    ForwardReferenceChangeSetGenerateStep.class,  // MUST run first - generates changeset
    ForwardReferenceChangeSetIngestStep.class     // MUST run second - imports changeset
})
public class ForwardReferenceChangeSetTestSuite {
    // Suite configuration only - no test methods needed
    // JUnit will execute the selected test classes in the order specified
}

